server:
  port: 8888 #项目访问端口号

#rabbitmq相关
spring:
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
    #发布确认高级配置
    publisher-confirm-type: CORRELATED
    publisher-returns: true